login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
        path('', views.login, name='login'),
        path('signup/', views.signup, name='signup'),
        path('logout/', views.logout, name='logout'),
        path('password_reset/', views.password_reset, name='password_reset'),
        path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
        path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
]

pizza_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .api import PizzaList, PizzaDetail, UserProfileList, UserList
from login_app import urls as login_app

app_name = "pizza_app"

urlpatterns = [
    path('', login_app.views.login, name='login'),
    path('customer_page', views.customer_page, name='customer_page'),
    path('employee_page/', views.employee_page, name='employee_page'),
    path('user_profile/', views.user_profile, name='user_profile'),  # new
    path('base/', views.base, name='base'),
    path('edit_pizza/<int:pk>/', views.edit_pizza, name='edit_pizza'),
    path('delete_pizza/', views.delete_pizza, name='delete_pizza'),
    path('update_pizza/', views.update_pizza, name='update_pizza'),

    path('place_order/', views.place_order, name='place_order'),
    path('clear_order/', views.clear_order, name='clear_order'),
    path('thank_you/<int:pk>/', views.thank_you, name='thank_you'),

    #API
    path('api/v1/pizzas', PizzaList.as_view()),
    path('api/v1/pizzas/<int:pk>/', PizzaDetail.as_view()),
    path('api/v1/userprofiles', UserProfileList.as_view()),
    path('api/v1/users', UserList.as_view()),
    
    path('edit_customers/', views.edit_customers, name='edit_customers'),

    path('admin/orders', views.orders_page, name='orders_page'),
    path('admin/orders/<int:pk>', views.single_order, name='single_order'),
    path('accept_order', views.accept_order, name='accept_order'),
    path('fulfill_order', views.fulfill_order, name='fulfill_order'),

]

pizza_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza_app.urls')),
    path('accounts/', include('login_app.urls')),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizza_app/models.py
from uuid import uuid4
from django.contrib.auth.models import User
from django.db import models
import random, _datetime
import uuid

# CHANNELS FOR NOTIFICATION WHEN ORDER IS PLACED
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

# DJANGO RQ FOR EMAIL WHEN ORDER IS PLACED
import django_rq
from . messaging import admin_order_email, user_order_email

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    telephone = models.CharField(max_length=35, default=None, blank=True, null=True)
    isEmployee = models.BooleanField(default=False)

    @classmethod
    def create_userprofile(cls, user): # For signals
        userProfile = cls()
        userProfile.user = user
        userProfile.save()

        return userProfile

    def __str__(self):
        return f'{self.user}'

class Pizza(models.Model):
    name = models.CharField(max_length=250)
    text = models.CharField(max_length=250)
    price = models.IntegerField(default=0)
    cover = models.ImageField(upload_to='images', default='default.jpg')

    @classmethod
    def create(cls, name, text, price, cover):
        pizza = cls()
        pizza.name = name
        pizza.text = text
        pizza.price = price
        pizza.cover = cover

        pizza.save()

        return pizza

    def update_pizza(self, name, text, price):
        self.name = name
        self.text = text
        self.price = price

        self.save()

        return self

    def __str__(self):
        return f"{self.name}"

class Topping(models.Model):
     item = models.CharField(max_length=64, unique=True, blank=False)
     price = models.IntegerField(default=0)

     def __str__(self):
        return f'{self.item}'


class LineItem(models.Model):
    item = models.ForeignKey(Pizza, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=1)
    line_item_order = models.ForeignKey('Order', on_delete=models.CASCADE, null=True, related_name='+')
    toppings = models.ManyToManyField(Topping, blank=True)
    
    def __str__(self):
        toppings = ""
        for topping in self.toppings.all():
            toppings = toppings + topping.item + ", "

        if toppings == "":
            return f"{self.quantity}x {self.item.name}"
        else:
            return f"{self.quantity}x {self.item.name} with {toppings}"
        

class Order(models.Model):
    status = (
        ('Pending', 'Pending'),
        ('Accepted', 'Accepted'),
        ('Delivered', 'Delivered'),
    )

    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date_time = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(
        choices=status, default='Pending', max_length=250)
    final_line_items = models.ManyToManyField(LineItem, blank=True)
    total_price = models.IntegerField(default=0)
    line_items_total_quantity = models.IntegerField(default=0)
    is_placed = models.BooleanField(default=False)

    @classmethod
    def start_new_order(cls, customer):
        order = cls()
        order.customer = customer
        order.is_placed = False
        order.save()

        return order

    def place_order(self):
        self.is_placed = True
        self.save()

        self.create_order_notification()
        self.send_order_confirmation_emails()

        return self

    def create_line_item(self, pizza_id, order, quantity):
        pizza = Pizza.objects.get(pk=pizza_id)
        
        # line_item, created = LineItem.objects.get_or_create(item=pizza, line_item_order=order)

        line_item = LineItem.objects.create(item=pizza, line_item_order=order)

        line_item.quantity = quantity
        line_item.save()
        
        self.final_line_items.add(line_item)

        self.get_order_total()

        return line_item

    def get_order_total(self):
        # self.final_line_items 

        self.total_price = 0
        self.line_items_total_quantity = 0

        for final_line_item in self.final_line_items.all():
            self.total_price+= final_line_item.item.price * final_line_item.quantity
            self.line_items_total_quantity+= final_line_item.quantity
            self.save()
            for topping in final_line_item.toppings.all():
                self.total_price+= topping.price * final_line_item.quantity
                self.save()

        return self

        # def create_line_item(self, pizza_id, order):
        # pizza = Pizza.objects.get(pk=pizza_id)
        
        # # line_item, created = LineItem.objects.get_or_create(item=pizza, line_item_order=order)

        # line_item, created = LineItem.objects.create(item=pizza, line_item_order=order)
        
        # if created:
        #     self.final_line_items.add(line_item)
        # else:
        #     line_item.quantity+=1
        #     line_item.save()
        
        # self.line_items_total_quantity = 0
        # self.total_price = 0

        # for final_line_item in self.final_line_items.all():
        #     self.total_price+= final_line_item.item.price * final_line_item.quantity
        #     self.line_items_total_quantity+= final_line_item.quantity
        #     self.save()

        # return line_item

    def clear_line_items(self):
        self.final_line_items.all().delete()
        self.line_items_total_quantity = 0
        self.total_price = 0
        self.save()


    def create_order_notification(self):
        channel_layer = get_channel_layer()
        data = "Order #"+ str(self.pk) + " placed."

        async_to_sync(channel_layer.group_send)(
            str("Notification_Group"),
            {
                "type": "notify",
                "text": data,
            },
        )

    def order_status_change(self):
        channel_layer = get_channel_layer()
        data = self.order_status

        async_to_sync(channel_layer.group_send)(
            str("Order_Status_Group"), 
            {
                "type": "update_status",
                "text": data,
            },
        ) 

    def send_order_confirmation_emails(self):
        django_rq.enqueue(admin_order_email, {
               'order_id' : str(self.pk),
               'email' : 'joshkap2015@gmail.com',
               'order': self
            })
        django_rq.enqueue(user_order_email, {
               'order_id' : str(self.pk),
               'email' : 'joshkap2015@gmail.com',
            })

    def __str__(self):
        return f"Order #{self.pk} {'Placed' if self.is_placed else 'Draft'}"

pizza_app/forms.py
from django import forms
from .models import Pizza

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name', 'text', 'price', 'cover']

pizza_app/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.db.utils import IntegrityError
from django.contrib.auth import get_user_model
from .models import UserProfile, Pizza, Order, Topping
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
import random
from django.urls import reverse
from django.shortcuts import redirect
from .forms import PizzaForm
from django.views.generic import CreateView

# EMAILS
import django_rq

def employee_required(login_url=None):
    return user_passes_test(isEmployee, login_url=login_url)

def isEmployee(user):
    user_profile = UserProfile.objects.get(user=user)
    return user_profile.isEmployee

@login_required
@employee_required(login_url="/customer_page")
def index(request):
        return HttpResponseRedirect(reverse('pizza_app:employee_page'))

@login_required
def customer_page(request):
    pizzas = Pizza.objects.all()
    user_profile = UserProfile.objects.get(user=request.user)
    toppings = Topping.objects.all()

    order = Order.objects.filter(customer=request.user).last()
    if(order):
        if(order.is_placed):
            order = Order.start_new_order(request.user)
            print("one order has already been placed, creating a new one")
    else:
        order = Order.start_new_order(request.user)
        print("No order found, starting new order")

    if request.method == 'POST' and 'addBtn' in request.POST:
        pizza_id = request.POST['pizza_id']
        pizza_quantity = request.POST['pizza_quantity']

        line_item = order.create_line_item(pizza_id, order, pizza_quantity)


        for topping in Topping.objects.all():
            if topping.item in request.POST:
                
                line_item.toppings.add(topping)
                print(f"Added {topping.item} to line item")

        order.get_order_total()

        # if 'Pepperoni' in request.POST :
        #     # Do something if pepperoni is POSTed (checked)
        #     pepperoni = Topping.objects.get(pk=3)
        #     line_item.toppings.add(pepperoni)

        # if 'Extra Cheese' in request.POST :
        #     extra_cheese = Topping.objects.get(pk=1)
        #     line_item.toppings.add(extra_cheese)

        # if 'Salat' in request.POST :
        #     salat = Topping.objects.get(pk=2)
        #     line_item.toppings.add(salat)

        return HttpResponseRedirect(request.META['HTTP_REFERER'])              
    
    if request.method == 'POST' and 'clearBtn' in request.POST:
        order_id = request.POST['order_id']

        order.clear_line_items()

        return HttpResponseRedirect(request.META['HTTP_REFERER'])             

    if request.method == 'POST' and 'placeBtn' in request.POST:
        order_id = request.POST['order_id']
        order.place_order()

        return redirect('thank_you/'+ str(order.pk))              
        
    context = {
        'toppings' : toppings,
        'pizzas': pizzas,
        'user_profile': user_profile,
        'order': order,
    }
    return render(request, 'pizza_app/customer_page.html', context)


@login_required
def user_profile(request):
    if request.method == 'GET':
        userProfile = UserProfile.objects.get(user=request.user)
        context = {
            'userProfile': userProfile,
        }
    return render(request, 'pizza_app/user_profile.html', context)


@login_required
def thank_you(request, pk):
    order = get_object_or_404(Order, pk=pk)
    context = {
        'order': order,
    }
    return render(request, 'pizza_app/thank_you.html', context)


@login_required
@employee_required(login_url="/customer_page")
def employee_page(request):
    user_profile = UserProfile.objects.get(user=request.user)
    pizzas = Pizza.objects.all()
    form= PizzaForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()

    context = {
        'pizzas': pizzas,
        'user_profile': user_profile,
        'form': form,
    }
    return render(request, 'pizza_app/employee_page.html', context)

@login_required
def base(request):
    user_profile = UserProfile.objects.filter(user=request.user)
    context = {
        'user_profile': user_profile,
    }
    return render(request, 'pizza_app/base.html', context)

@login_required
@employee_required(login_url="/customer_page")
def edit_pizza(request, pk):
    pizza = get_object_or_404(Pizza, pk=pk)
    context = {
        'pizza': pizza,
    }
    return render(request, 'pizza_app/edit_pizza.html', context)

def delete_pizza(request):
    pizza_id = request.POST['pizza_id']
    pizza = get_object_or_404(Pizza, pk=pizza_id)
    pizza.delete()

    return HttpResponseRedirect(reverse('pizza_app:employee_page'))

def update_pizza(request):
    pizza_id = request.POST['pizza_id']
    pizza = get_object_or_404(Pizza, pk=pizza_id)
    pizza.update_pizza(request.POST['pizza_name'], request.POST['pizza_text'], request.POST['pizza_price'])

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
@employee_required(login_url="/customer_page")
def edit_customers(request):
    customers = get_user_model().objects.all()
    profiles = UserProfile.objects.all()
    context = {
        'customers': customers,
        'profiles': profiles,
    }
    return render(request, 'pizza_app/edit_customers.html', context)


# Admin/orders
@login_required
@employee_required(login_url="/customer_page")
def orders_page(request):
    user_profile = UserProfile.objects.get(user=request.user)
    orders = Order.objects.all()

    context = {
        'orders' : orders
    }

    return render(request, 'pizza_app/orders.html', context)

# Admin/Orders/<int:pk> Page (SINGLE order page)
@login_required
@employee_required(login_url="/customer_page")
def single_order(request, pk):
    order = get_object_or_404(Order, pk=pk)

    return render(request, 'pizza_app/single_order.html', {"order":order})

def accept_order(request):
    if request.method == 'POST':
        order_pk = request.POST['order_pk']
        order = get_object_or_404(Order, pk=order_pk)
        order.order_status = "Accepted"
        order.save()

        order.order_status_change()
        
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
        

def fulfill_order(request):
    order_pk = request.POST['order_pk']
    order = get_object_or_404(Order, pk=order_pk)
    order.order_status = "Fulfilled"
    order.save()

    order.order_status_change()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])



def clear_order(request):
    order_id = request.POST['order_id']
    order = get_object_or_404(Order, pk=order_id)
    order.clear_line_items()

    return HttpResponseRedirect(reverse('pizza_app:customer_page'))

def place_order(request):
    order_id = request.POST['order_id']
    order = get_object_or_404(Order, pk=order_id)
    order.place_order()
    
    #return HttpResponseRedirect(reverse('pizza_app:thank_you/' +str(order.pk)))
    return redirect('http://127.0.0.1:8000/thank_you/'+ str(order.pk))

pizza_app/templates/pizza_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'pizza_app/style.css' %}" media="screen" />
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Cardo&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div class="topbar">
    Free delivery on orders above 99kr
  </div>
  <nav class="topnav">
    <h1 class="shop-name">Pizza Express</h1>
    {% if user.is_authenticated and user_profile.isEmployee %}
      <a class="btn" href="{% url 'pizza_app:employee_page' %}">Home</a>
      <a class="btn" href="{% url 'pizza_app:edit_customers' %}">Edit Customer Profiles</a>
      <a class="nav-link2" href="{% url 'login_app:logout' %}">Log out <span data-feather="log-out"></a>
    {% elif user.is_authenticated and user_profile.isEmployee == False %}
      <a class="btn" href="{% url 'pizza_app:customer_page' %}">Home</a>
      <a class="nav-link2" href="{% url 'login_app:logout' %}">Log out <span data-feather="log-out"></a>
    {% endif %}

    {% comment %}
    Notifications div to be appended to by notifications
    {% endcomment %}
    <div
      style="margin-left:auto; width:100%; max-width:300px; position:relative; display:flex; flex-direction:column; align-items:center; justify-content:center;">
      <p style="display:block; margin:auto;"> Notifications</p>

      <div class="notifications-wrapper" style="width:100%;">
        <div class="notifications-container" style="position:absolute;">
          <!-- Notifications go here -->
        </div>
      </div>

    </div>

    {% if user.is_not_authenticated %}
      <a class="nav-link2" href="{% url 'login_app:login' %}">Login <span data-feather="log-in"></a>
      <a class="btn" href="{% url 'login_app:signup' %}">Sign up</a>
    {% endif %}

  </nav>

  {% block content %} 

  {% endblock %} 
  
  <script>
    /* Connecting to notifications socket, same as routing.py in notifications folder ... */
    const notificationSocket = new WebSocket(
      'ws://'
      + window.location.host
      + '/ws/notifications/'
    );

    // Socket should be connected now, now we can run functions on the socket instance.

    // Socket On receive message Functionality
    notificationSocket.onmessage = function (e) {
      console.log('message', e)
      console.log(e.data) // Access the notification data
      console.log("e.data" + e.data)

      const notificationContainer = document.querySelector(".notifications-container");

      let notificationDiv = document.createElement("div");


      notificationDiv.classList.add("notification-div");

      notificationDiv.innerHTML = "<p class='notification-p'>" + e.data + "</p>"

      notificationContainer.appendChild(notificationDiv)

      /* setTimeout(() => {
        notificationDiv.remove();
      }, 5000);
      */

    }

    // Socket Connet Functionality
    notificationSocket.onopen = function (e) {
      console.log('Notification socket - open', e)
      console.log('Socket is opened.')
    }

    // Socket Error Functionality
    notificationSocket.onerror = function (e) {
      console.log('Notification socket - error', e)
    }

    // Socket close Functionality
    notificationSocket.onclose = function (e) {
      console.log('Notification socket - closed', e)
    }
  </script>



  <style>
    .notification-div {
      background-color: white;
      padding-top: 10px;
      padding-bottom: 10px;
      width: 100%;
      max-width: 200px;
      padding-left: 20px;
      padding-right: 20px;
      box-shadow: 10px 10px 25px rgba(0, 0, 0, .14);
      transition: box-shadow .3s ease-in-out;
      cursor: pointer;
      margin: 0 auto;
    }

    .notifications-container {
      display: grid;
      width: 100%;
      grid-row-gap: 10px;
      transition: all .3s ease-in-out;
    }

    .topbar {
      border-bottom: 1px solid black;
      text-align: center;
      font-family: 'Montserrat', sans-serif;
      padding-top: 10px;
      padding-bottom: 10px;
      font-size: 12px;
    }

    .topnav a {
      color: black;
      text-decoration: none;
      display: flex;
      align-items: center;
      margin-left: 10px;

    }

    .topnav {
      display: flex !important;
      padding-left: 40px;
      padding-right: 40px;
      border-bottom: 2px solid white;
    }

    .shop-name {
      font-size: 30px;
      color: black;
      font-family: 'Cardo', serif;
      padding: 0;
      margin-right: 20px;
    }

    .topnav img {
      width: 40px;
      height: 40px;
    }
  </style>
</body>

</html>

pizza_app/templates/pizza_app/customer_page.html
{% extends 'pizza_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="user_page">
    {% csrf_token %}
    <div class="menu_container">
        {% load static %}

        <p class="greeting-text">Hello <b>{{ user.username }}</b> ({{ user_profile.user_status }})</p>
        <a class="profile-details-btn" style="color:black;" href="{% url 'pizza_app:user_profile' %}"
            style="color:white !important">View Profile Details</a>

        <form action="">

        </form>
        <div class="hero-wrapper">
            <div>
                <h1 class="hero-header">Traditional fresh pizza since 2020.</h1>
            </div>
            <div style="width:100%;">
                <img class="hero-img" src="{% static 'pizza_app/img/ingredients.png' %}" alt="">
            </div>
        </div>
        <div class="pizzas-bg">
            <div class="pizzas-wrapper">
                
                   
                    {% for pizza in pizzas %}
                    <form method="POST">
                        {% csrf_token %}
                    <div class="pizza-block">
                        <input type="hidden" name="pizza_id" value="{{ pizza.pk }}" />
                        <input type="hidden" name="pizza_price" value="{{pizza.price}}" />
                        <input type="hidden" name="pizza_name" value="{{pizza.name}}" />

                        <div class="pizza-content">
                            <div>
                                <h2 class="pizza-name">{{ pizza.name }}</h2>
                                <p>{{ pizza.price }} kr.</p>
                                <p class="pizza-text">{{ pizza.text }}</p>

                            </div>
                            <div class="pizza-img">
                                <img src="{{ pizza.cover.url }}" alt="{{ pizza.name }}">
                            </div>
                        </div>
                        
                        <label for="topping-choice">Additional toppings</label>
                        <div style="display:flex; justify-content:space-between;">
                            {% for topping in toppings %}
                            <label style="font-size:12px;">
                                <input type="checkbox" id="{{ topping.pk }}" name="{{ topping.item }}" onchange="changeValue(this)">
                                {{ topping.item }} - {{ topping.price }} kr.
    
                            </label>
                            {% endfor %}
                            <!-- <script>
                                function changeValue(e) {
                                    if(e.value === "checked") {
                                        e.value = "unchecked"
                                        console.log(e.value)
                                    } else if (e.value === "unchecked"){
                                        e.value = "checked"
                                        console.log(e.value)
                                    }
                                }
                            </script> -->
                        </div>
                        <div>Quantity:</div> 
                        <div class="quantity-container" style="display:flex; align-items:center;">
                            <input type="number" id="quantity" name="pizza_quantity" min="1" value="1"> 
                        </div>

                        <style>

                            input[type=number]::-webkit-inner-spin-button {
                                opacity: 1; /* shows Spin Buttons per default (Chrome >= 39) */
                            }

                            #quantity {
                                width:40px;
                            }
                        </style>

                        <button style="margin-top:20px; padding:10px 30px" name="addBtn">Add To Order</button>
                    </div>
                       
                    </form>
                    {% endfor %}

                    <div> <b>Cart Total:</b> {{ order.line_items_total_quantity }} <b>Subtotal:</b> {{ order.total_price}} kr. </div>
                    <form method="POST">
                        {% csrf_token %}
                        <button class="button" name="clearBtn">Clear Cart</button>
                        <input type="hidden" name="order_id" value="{{order.pk}}">
                    </form>
                <form method="POST">
                    {% csrf_token %}
                    <button class="button" name="placeBtn">Place Order</button>
                    <input type="hidden" name="order_id" value="{{order.pk}}">
                </form>

            </div>
        </div>
        <a href="{% url 'login_app:logout' %}">Logout</a>
    </div>

    <div class="img_container">

    </div>
</section>

<style>
    .profile-details-btn {
        text-align: center;
        margin: 0 auto;
        display: block;
        font-size: 10px;
    }

    .greeting-text {
        text-align: center;
    }

    .pizzas-bg {
        background-color: #FFFBF6;
        padding-top: 40px;
        padding-bottom: 40px;
    }

    p {
        font-family: 'Montserrat', sans-serif;
    }

    .pizzas-wrapper {
        max-width: 1000px;
        margin: 0 auto;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-column-gap: 40px;
    }

    .hero-wrapper {
        max-width: 1000px;
        margin: 0 auto;
        display: grid;
        grid-template-columns: 1fr 1fr;
    }

    .hero-img {
        width: 70%;
        display: block;
        margin: 0 auto;
    }

    .hero-header {
        font-size: 86px;
        line-height: 90px;
        font-family: 'Cardo', serif;
        font-weight: 400;
    }

    .pizza-name {
        font-family: 'Cardo', serif;
        margin-bottom: 1rem;
        font-weight: 400 !important;
    }

    .pizza-text {
        color: #746b60;
        line-height: 1.5em;
        height: 3em;
        overflow: hidden;

        text-overflow: ellipsis !important;

    }

    .pizza-content {
        display: grid;
        grid-template-columns: 1fr 0.5fr;
    }

    .pizza-img {
        width: 100%;
    }

    .pizza-img img {
        width: 60%;
        display: block;
        margin-left: auto;

    }

    .user_page {
        background-color: #FAF3EC;

    }

    .pizza-block {

        padding: 20px;
        border-bottom: 1px solid #746b605e;
    }


    .pizza-block:hover .pizza-name {
        text-decoration: underline;
    }
</style>

{% endblock %}

pizza_app/templates/pizza_app/edit_customers.html
{% extends 'pizza_app/base.html' %}

{% block title %}Login{% endblock %}

{%block content %}
<h1>Edit User</h1>


<form method="POST">

    {% for customer in customers %}
    <h2>Hello {{ customer.username }}. {{ customer.email }}
        {% for profile in profiles %}
        {{ profile.user_status }}</h2>
    {% endfor %}

</form>
<hr />
<a href="{% url 'pizza_app:employee_page' %}">Home</a>

{% endblock %}

pizza_app/templates/pizza_app/edit_pizza.html
{% extends 'pizza_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="edit_pizza">
  <h1>Edit Pizza</h1>


  <form method="POST">
    {% csrf_token %}
    <input type="hidden" name="pizza_id" value="{{pizza.pk}}" placeholder="{{pizza.pk}}" />
    <label for="lname">Pizza name:</label><br>
    <input type="text" name="pizza_name" value="{{pizza.name}}" placeholder="{{pizza.name}}" /> <br>
    <label for="lname">Pizza description:</label><br>
    <textarea type="text" name="pizza_text" value="{{pizza.text}}" placeholder="{{pizza.text}}"></textarea> <br>
    <label for="lname">Pizza Price:</label><br>
    <input type="number" name="pizza_price" value="{{pizza.price}}" placeholder="{{pizza.price}}" /><br><br>

    <button class="button" formaction="{% url 'pizza_app:delete_pizza' %}">Delete pizza</button>
    <button class="button" formaction="{% url 'pizza_app:update_pizza' %}">Update pizza</button>

    <input type="hidden" name="pizza_id" value="{{pizza.pk}}">

  </form>
  <hr />
  <a class="home-btn" href="{% url 'pizza_app:employee_page' %}">Home</a>

</section>

{% endblock %}

pizza_app/templates/pizza_app/orders.html
{% extends 'pizza_app/base.html' %}

{% block title %}Pizza Express ~ Orders ~ Django{% endblock %}

{% block content %}


<section class="orders-page">
<div style="font-size:40px; text-align:center; margin: 40px auto;">
    Orders Page
</div>

<div style="display:grid; max-width:1000px; width:100%; margin: 0 auto;">


<div style="display:grid; grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;  grid-row-gap:20px;">
    <div>Order Id</div>
    <div>Date</div>
    <div>Customer</div>
    <div>Total</div>
    <div>Order Status</div>
    <div></div>

    {% for order in orders reversed %}
    <div>{{ order.pk }}</div>
    <div>{{ order.order_date_time}} </div>
    <div>{{ order.customer }} </div>
    <div>{{ order.total_price }} </div>
    <div>{{order.order_status}} </div>
    <a href="{% url 'pizza_app:single_order' order.pk %}">View Order</a href="">
    {% endfor %}

</div>




</div>

</section>

{% endblock %}